### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Gater73** [Jabrils/TelloTV#4]
Traceback (most recent call last):
  File "C:\Users\Gabri\Desktop\TelloTV-master\TelloTV.py", line 1, in <module>
    from djitellopy import Tello
  File "C:\Users\Gabri\Desktop\TelloTV-master\djitellopy\__init__.py", line 1, in <module>
    from djitellopy.tello import Tello, BackgroundFrameRead
  File "C:\Users\Gabri\Desktop\TelloTV-master\djitellopy\tello.py", line 5, in <module>
    import cv2
  File "C:\Users\Gabri\Desktop\TelloTV-master\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: %1 its not a Win32 valid program

Also got this trynig to install the requirements.

Downloading/unpacking requirements.txt
  Could not find any downloads that satisfy the requirement requirements.txt
Cleaning up...
No distributions at all found for requirements.txt
Storing debug log for failure in C:\Users\Gabri\pip\pip.log

**Comment by nlona** [comment]
python3 TelloTV.py 
Traceback (most recent call last):
  File "TelloTV.py", line 46, in <module>
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2.cv2' has no attribute 'face'


any idea about this seems cannot find a face?

Why did not try to put a raspberry zero in between and on board of the tello and run on the raspberry this pithon code?

**Comment by abidwaqar** [comment]
@nlona , I had the same error and this resolved the error for me:
pip uninstall opencv-contrib-python
pip install --user opencv-contrib-python
